### ISSUE TITLE
Multiple Influx Buckets

### ISSUE THREAD

**Issue by collinbrake** [simpleiot/simpleiot#465]
@cbrake I created another bucket in your test instance and now `siot_run log` is crashing. Not sure if it is tied to that or another issue, but coincidental:

```2022/12/08 14:49:03 NODE: sync to portal (sync) (6a955e0f-3307-4fb8-9134-f03c30d752f8)
   - POINT: T:syncCount V:19.000 2022-12-08T19:49:03Z
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xdfc66f]

goroutine 9 [running]:
github.com/simpleiot/simpleiot/client.String(0x410980?, 0xc00014a2a0)
	/home/ventrac/siot-workspace/simpleiot/client/debug.go:48 +0x10f
github.com/simpleiot/simpleiot/client.Dump(0xc000496680?, 0x0?)
	/home/ventrac/siot-workspace/simpleiot/client/debug.go:14 +0x3b
github.com/simpleiot/simpleiot/client.Log.func4(0xc000496680?)
	/home/ventrac/siot-workspace/simpleiot/client/debug.go:100 +0x3f
github.com/nats-io/nats%2ego.(*Conn).waitForMsgs(0xc0002f8600, 0xc000496680)
	/home/ventrac/go/pkg/mod/github.com/nats-io/nats.go@v1.20.0/nats.go:2839 +0x739
created by github.com/nats-io/nats%2ego.(*Conn).subscribeLocked
	/home/ventrac/go/pkg/mod/github.com/nats-io/nats.go@v1.20.0/nats.go:4069 +0x825
```

Also getting a lot of ignoring edge points messages:
```
2022/12/08 14:51:53 sync sync to portal: syncing node: Test CAN Bus Client, hash up: 0x7aa1ed88, down: 0x636ed8de 
2022/12/08 14:51:53 Ignoring edge point due to timestamps:  074975c9-18fc-4a8c-987c-5e75e6bc8b47 T:tombstone V:0.000 O:af43f854-9729-4ee4-88e1-9b47fc9d1bed 2022-12-06T19:34:01Z
2022/12/08 14:52:03 sync sync to portal: syncing node: Test CAN Bus Client, hash up: 0x3b836412, down: 0xb8a7e8c8 
2022/12/08 14:52:03 Ignoring edge point due to timestamps:  074975c9-18fc-4a8c-987c-5e75e6bc8b47 T:tombstone V:0.000 O:af43f854-9729-4ee4-88e1-9b47fc9d1bed 2022-12-06T19:34:01Z
2022/12/08 14:52:13 sync sync to portal: syncing node: Test CAN Bus Client, hash up: 0x7e1864e4, down: 0x1bac8de5 
2022/12/08 14:52:13 Ignoring edge point due to timestamps:  074975c9-18fc-4a8c-987c-5e75e6bc8b47 T:tombstone V:0.000 O:af43f854-9729-4ee4-88e1-9b47fc9d1bed 2022-12-06T19:34:01Z
2022/12/08 14:52:23 sync sync to portal: syncing node: Test CAN Bus Client, hash up: 0x6ecdc8ac, down: 0xede94476 
2022/12/08 14:52:23 Ignoring edge point due to timestamps:  074975c9-18fc-4a8c-987c-5e75e6bc8b47 T:tombstone V:0.000 O:af43f854-9729-4ee4-88e1-9b47fc9d1bed 2022-12-06T19:34:01Z
```

**Comment by cbrake** [comment]
it might be related to moving the device into the group on the server.

Can you send me the siot.sqlite db file and I'll try to reproduce the crash here?

**Comment by cbrake** [comment]
I see the log issue, fixing how ...

**Comment by cbrake** [comment]
can you merge master and see if you still get the log crash?

**Comment by collinbrake** [comment]
@cbrake now I am seeing this when I run siot_run (hadn't restarted the main process...) probably on my end?

```
2022/12/08 15:03:15 NATS edge connect to: wss://portal.simpleiot.org:443, auth enabled: yes
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdf7979]

goroutine 99 [running]:
github.com/simpleiot/simpleiot/client.(*CanBusClient).Start.func2()
	/home/ventrac/siot-workspace/simpleiot/client/can.go:130 +0x39
github.com/simpleiot/simpleiot/client.(*CanBusClient).Start.func3()
	/home/ventrac/siot-workspace/simpleiot/client/can.go:134 +0x70
github.com/simpleiot/simpleiot/client.(*CanBusClient).Start(0xc0000e01c0)
	/home/ventrac/siot-workspace/simpleiot/client/can.go:152 +0x21c
github.com/simpleiot/simpleiot/client.(*clientState[...]).start.func2()
	/home/ventrac/siot-workspace/simpleiot/client/client-state.go:119 +0x71
created by github.com/simpleiot/simpleiot/client.(*clientState[...]).start
	/home/ventrac/siot-workspace/simpleiot/client/client-state.go:117 +0x8da
```

**Comment by collinbrake** [comment]
No, that is due to me trying to cancel my CAN socket context before it is created.

**Comment by cbrake** [comment]
yeah, the lifecycle stuff is hard -- probably the hardest part of programming. This is one reason why the SIOT client model will hopefully bring some value -- it takes care of most of the lifecycle issues and took quite a bit of work to get right.

**Comment by cbrake** [comment]
I'll do some tests with moving devices into a group on the upstream tomorrow -- I think there are still some issues there. 

Are you getting data into influx?

**Comment by collinbrake** [comment]
siot_run log seems to be working after pulling master. Thanks @cbrake!
