### ISSUE TITLE
app crash when network disconnected

### ISSUE THREAD

**Issue by cbrake** [simpleiot/simpleiot#625]
The Internet went out and then this happened:

```
Sep 28 13:30:28 ceres siot[1623759]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xae45f3]
Sep 28 13:30:28 ceres siot[1623759]: goroutine 229 [running]:
Sep 28 13:30:28 ceres siot[1623759]: github.com/simpleiot/simpleiot/client.EdgeConnect.func2.3(0xab8af8?, 0xc000a10500?, {0x150cb20?, 0xc000>
Sep 28 13:30:28 ceres siot[1623759]:         /scratch/simpleiot/go/client/edge.go:85 +0x33
Sep 28 13:30:28 ceres siot[1623759]: github.com/nats-io/nats%2ego.(*Conn).flusher.func1()
Sep 28 13:30:28 ceres siot[1623759]:         /home/cbrake/go/pkg/mod/github.com/nats-io/nats.go@v1.28.0/nats.go:3340 +0x28
Sep 28 13:30:28 ceres siot[1623759]: github.com/nats-io/nats%2ego.(*asyncCallbacksHandler).asyncCBDispatcher(0xc00070c160)
Sep 28 13:30:28 ceres siot[1623759]:         /home/cbrake/go/pkg/mod/github.com/nats-io/nats.go@v1.28.0/nats.go:2857 +0x1e
Sep 28 13:30:28 ceres siot[1623759]: created by github.com/nats-io/nats%2ego.Options.Connect in goroutine 151
Sep 28 13:30:28 ceres siot[1623759]:         /home/cbrake/go/pkg/mod/github.com/nats-io/nats.go@v1.28.0/nats.go:1502 +0x388
Sep 28 13:30:28 ceres systemd[1282]: siot.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 28 13:30:28 ceres systemd[1282]: siot.service: Failed with result 'exit-code'.
Sep 28 13:30:28 ceres systemd[1282]: siot.service: Consumed 38min 31.169s CPU time.
```

**Comment by cbrake** [comment]
also ran a test where I shut the network off on the machine, no crashes, so I suspect the issue was not a network disconnect, but corrupted packets due to a flaky network.
